language: julia

julia:
  - 1.2
  - nightly

os:
  - osx
  - linux

notifications:
  email: false

branches: master

jobs:
  include:
    - stage: "Documentation"
      julia: nightly
      os: osx
      script:
        # - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
        #                                        Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
