language: julia

julia:
  - 1.2
  - nightly

os:
  - osx
  - linux

notifications:
  email: false

branches:
  only:
    - master
    - gh-pages

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
