site_name:        Manifolds.jl
repo_url:         https://github.com/macorstanje/Manifolds.jl
site_description: Description...
site_author:      macorstanje

theme: readthedocs

# extra_css:
#   - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Manual: manual.md
  - Library: library/library.md
